Implement encryption
DiviPeople/chen-api pull request #7
Opened 2023-05-25 13:18 UTC by Nsenixx

2023-05-25 14:23 UTC, Themanwhosmellslikesugar requested changes

2023-05-25 14:23 UTC, Themanwhosmellslikesugar commented on src/encryption.rs
> +use rand::{distributions::Alphanumeric, Rng}; // 0.8
Лишний комментарий

2023-05-25 14:23 UTC, Themanwhosmellslikesugar commented on src/encryption.rs
> +use std::env;
Порядок импортов соблюсти

2023-05-25 14:23 UTC, Themanwhosmellslikesugar commented on src/encryption.rs
> +pub fn encrypt(mut pass: String) -> (String, String) {
Переделай в ассоциированный метод с структуре User

2023-05-25 14:23 UTC, Themanwhosmellslikesugar commented on src/entity/users.rs
>      pub salt: Option<String>,
Убрать Option

2023-05-29 21:58 UTC, V1ammer requested changes

2023-05-29 21:58 UTC, V1ammer commented on Cargo.toml
> +rust-argon2 = "0.8"
использование старой версии библиотеки
```suggestion
rust-argon2 = "1.0.0"
```

2023-05-29 21:58 UTC, V1ammer commented on src/config.rs
> +use argon2::{self, Config, ThreadMode, Variant, Version};
Порядок импортов соблюсти
```suggestion
use argon2::{self, Config, ThreadMode, Variant, Version};
use color_eyre::Result;
use dotenvy::dotenv;
use serde::Deserialize;
```

2023-05-29 21:58 UTC, V1ammer commented on src/config.rs
> +impl AppConfig{
неправильное оформление кода
```suggestion
impl AppConfig {
```

2023-05-29 21:58 UTC, V1ammer commented on src/entity/users.rs
> +use serde::{Deserialize};
неправильное оформление кода
```suggestion
use serde::Deserialize;
```

2023-05-29 21:58 UTC, V1ammer commented on src/entity/users.rs
> +use rand::distributions::{Alphanumeric, DistString};
Порядок импортов соблюсти
```suggestion
use rand::distributions::{Alphanumeric, DistString};
use sea_orm::{entity::prelude::*, Set};
use serde::{Deserialize};
```

2023-05-29 21:58 UTC, V1ammer commented on src/entity/users.rs
> +}
Нужна пустая строчка в конце файла
```suggestion
}

```

2023-05-30 11:34 UTC, V1ammer requested changes

2023-05-30 11:34 UTC, V1ammer commented on Cargo.toml
> +rand = "0.8.4"
использование старых версий библиотек
крэйт rand_core от версии 0.6 и ниже версии 0.6.2 содержит критические уязвимости
```suggestion
rust-argon2 = "1.0.0"
rand_core = { version = "0.6.4", features = ["std"] }
rand = "0.8.5"
```

2023-05-30 12:45 UTC, V1ammer commented on src/config.rs
> +pub const ARGON2_CONFIG: argon2::Config<'_> = Config {
Бесполезное использование префикса пути
```suggestion
pub const ARGON2_CONFIG: Config<'_> = Config {
```

2023-06-27 14:44 UTC, merged